animal_lists = {'leopard', 'fox', 'elephant', 'clam', 'caterpillar', 'sow',...
    'hog', 'bear', 'coyote', 'moose', 'mouse', 'skunk', 'rhinoceros', ...
    'shrimp', 'jaguar', 'calf', 'camel', 'oyster', 'flamingo', 'rabbit', ...
    'moth', 'penguin', 'gerbil', 'boar', 'shrew', 'squirrel', 'pigeon', 'pony', ...
    'turkey', 'cougar', 'python', 'stork', 'raven', 'ferret', 'snake', ...
    'mink', 'seal', 'goldfinch', 'fly', 'halibut', 'cobra', 'wren', ...
    'pheasant', 'emu', 'steer', 'wolf', 'spider', 'pig', 'koala', 'grouse', ...
    'otter', 'heron', 'baboon', 'rattlesnake', 'deer', 'canary', ...
    'alligator', 'seahorse', 'mole', 'ox', 'octopus', 'perch', 'worm', 'bat', ...
    'eel', 'hippopotamus', 'salmon', 'crane', 'bull', 'mosquito', 'mule', ...
    'bluegill', 'goat', 'kitten', 'wolverine', 'magpie', 'starfish', ...
    'seagull', 'raccoon', 'rooster', 'hedgehog', 'panda', 'peacock', ...
    'bass', 'platypus', 'hummingbird', 'aardvark', 'tuna', 'piranha', ...
    'snail', 'woodpecker', 'walleye', 'scorpion', 'chinchilla', 'sheep', ...
    'mallard', 'lark', 'antelope', 'eagle', 'starling', 'minnow', 'goose', ...
    'herring', 'jellyfish', 'yak', 'newt', 'buffalo', 'toad', 'lamb', ...
    'whale', 'frog', 'falcon', 'barracuda', 'dove', 'lemur', 'manatee', ...
    'horse', 'locust', 'quail', 'weasel', 'shark', 'hare', 'centipede', ...
    'chicken', 'caribou', 'bee', 'mongoose', 'porpoise'};

SD_CORRECT.four_legs = {'chimpanzee','gorilla','ape','muskrat','dromedary',...
    'mink','lamb','kitten','lion','chipmunk','reindeer','llama','cat','elk',...
    'crocodile','tortoise','ram','turtle','salamander','horse','deer',...
    'jackal','guineapig','tiger','leopard','fox','elephant','sow','hog', ...
    'bear','coyote','moose','mouse','skunk','rhinocerous','jaguar','calf',...
    'bobcat','hyena','beaver','rat','cow','porcupine','iguana','gazelle',...
    'zebra','goat','anteater','hamster','groundhog','monkey','pig','mule',...
    'lizard','giraffe','cheetah','panther','dog','badger','sloth','sheep',...
    'opposum','steer','camel','rabbit','gerbil','boar','shrew','squirrel',...
    'pony','cougar'};

SD_CORRECT.USED_BY_PEOPLE = {'PIKE', 'DROMEDARY', 'MINK', 'LAMB', 'COD', ...
    'BASS', 'KITTEN', 'TROUT', 'PERCH', 'DUCK', 'LLAMA', 'CAT', 'GOLDFISH', ...
    'TURTLE', 'PARRAKEET', 'HORSE', 'CHICKEN', 'DEER', 'CATFISH', 'SARDINE',...
    'GUINEAPIG', 'FOX', 'CLAM', 'SOW', 'HOG', 'SHRIMP', 'CALF', 'PARROT', ...
    'BEAVER', 'SQUID', 'COW', 'GOOSE', 'GOAT', 'HAMSTER', 'FLOUNDER', 'PIG', ...
    'SALMON', 'MULE', 'CARP', 'DOG', 'SUNFISH', 'SHEEP', 'OSTRICH', 'TUNA', ...
    'STEER', 'LOBSTER', 'CAMEL', 'OYSTER', 'RABBIT', 'GERBIL', 'PONY', 'TURKEY'};

SD_CORRECT.FOUND_IN_US = {'MUSKRAT', 'OWL', 'PIKE', 'MINK', 'LAMB', ...
    'CROW', 'COD', 'BASS', 'KITTEN', 'PELICAN', 'BLUEJAY', 'ROBIN', 'TROUT', ...
    'CHIPMUNK', 'PERCH', 'DUCK', 'SPARROW', 'CARDINAL', 'CAT', 'GRASSHOPPER', ...
    'ELK', 'GOLDFISH', 'RAM', 'TURTLE', 'SALAMANDER', 'PARRAKEET', ...
    'COCKROACH', 'HORSE', 'CHICKEN', 'DEER', 'CATFISH', 'HAWK', ...
    'GUINEAPIG', 'TERMITE', 'BUTTERFLY', 'FOX', 'CLAM', ...
    'CATERPILLAR', 'SOW', 'HOG', 'BEAR', 'COYOTE', 'MOOSE', ...
    'MOUSE', 'SKUNK', 'SHRIMP', 'CALF', 'PARROT', 'BOBCAT', ...
    'BEAVER', 'GNAT', 'DOLPHIN', 'RAT', 'COW', 'WASP', 'PORCUPINE', ...
    'GOOSE', 'GOAT', 'SPIDER', 'HAMSTER', 'FLOUNDER', 'GROUNDHOG', ...
    'DRAGONFLY', 'PIG', 'SALMON', 'MULE', 'LIZARD', 'CARP', 'FINCH', 'SWAN', ...
    'ANT', 'DOG', 'BADGER', 'SUNFISH', 'SHEEP', 'CRICKET', 'OPPOSUM', ...
    'BEETLE', 'TUNA', 'STEER', 'CHICKADEE', 'LOBSTER', 'OYSTER', ...
    'FLAMINGO', 'RABBIT', 'MOTH', 'GERBIL', 'BOAR', 'SHREW', 'SQUIRREL', ...
    'PIGEON', 'PONY', 'TURKEY', 'COUGAR', 'STORK'};

