function sFiles_rej = bs_preprocess_ICA_reject_trials(sFiles)
% Script generated by Brainstorm (08-Mar-2022)

% Process: FieldTrip: process_ft_ica_clean
sFiles_ic = bst_process('CallProcess', 'process_ft_ica_clean', sFiles, [], ...
    'sensortype', 'MEG', ...  % MEG
    'lay',        'neuromag');  % neuromag

sFiles_rej = bst_process('CallProcess', 'process_ft_reject_trials', sFiles_ic, [], ...
    'sensortype', 'MEG', ...  % MEG
    'mrej',       'Auto', ...  % Automatic
    'arej',       0.9);

end
