% clc

%%
fprintf(['Login to WinSCP, connect to the Squiggles VM (ip: 141.106.26.29), and copy:\n\n' ...
    'dataset_DL_ready_win_m250_p500.mat\n\n' ...
    'From:\n' ...
    'Z:\\LAB_MEMBERS\\Vahab\\Github\\MCW-MEGlab\\MCW_MEGlab_git\\Projects\\Deeplearning_spike\\MEGneto\n\n' ...
    'To:\n' ...
    '/home/vyoussofzadeh/github/MCW-MEGlab/MCW-MEGlab/Projects/Deeplearning_spike/Squiggles\n']);


% 

disp('Bandpass filter')
fprintf(['Login to WinSCP, connect to the Squiggles VM (ip: 141.106.26.29), and copy:\n\n' ...
    'dataset_DL_ready_win_m250_p500_bp5_50.mat\n\n' ...
    'From:\n' ...
    'on windows, Z:\AHW_SpikeAnalysis\Processed\Spike-NoSpike_Mat_files\n\n' ...
    'To:\n' ...
    'on server (Squiggles-VM), /home/vyoussofzadeh/Data/DL_model\n']);