function openSpikeList(~,~)
if isfield(ui,'spikeWin') && isvalid(ui.spikeWin)
    figure(ui.spikeWin); return;      % just pop it to front
end
ui.spikeWin = uifigure('Name','Spike list','Position',[100 100 200 250]);
uitable(ui.spikeWin, ...
    'Data', num2cell(ui.spikeT(:)), ...
    'ColumnName', {'Time (s)'}, ...
    'Position',[10 10 180 230], ...
    'CellSelectionCallback',@spikeSelect);
end
