function s01T1wRAI = do_read_coordinates(filename)

%% Import data from text file.
% Script for importing data from the following text file:
%
%    /data/MRI/idsc9005/stimulation_rois/002s01_T1w_RAI.1D
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2023/04/05 17:41:18

%% Initialize variables.
% filename = '/data/MRI/idsc9005/stimulation_rois/002s01_T1w_RAI.1D';

%% Format for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%7f%9f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', '', 'WhiteSpace', '', 'TextType', 'string',  'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
s01T1wRAI = dataArray(1:end-1);

%% Clear temporary variables
clearvars filename formatSpec fileID dataArray ans;