function [groups_labels, groups] = do_read_HCP_labels_bs()


% link: https://github.com/mne-tools/mne-python/blob/main/mne/datasets/utils.py


groups = {{'Primary Visual Cortex (V1)','V1'}, ...
    {'Early Visual Cortex','V2', 'V3', 'V4'}, ...
    {'Dorsal Stream Visual Cortex','V3A', 'V3B', 'V6', 'V6A', 'V7', 'IPS1'}, ...
    {'Ventral Stream Visual Cortex','V8', 'VVC', 'PIT', 'FFC', 'VMV1', 'VMV2', 'VMV3'}, ...
    {'MT+ Complex and Neighboring Visual Areas', 'V3CD', 'LO1', 'LO2', 'LO3', 'V4t', 'FST', 'MT', 'MST', 'PH'},...
    {'Somatosensory and Motor Cortex','4', '3a', '3b', '1', '2'},...
    {'Paracentral Lobular and Mid Cingulate Cortex','24dd', '24dv', '6mp', '6ma', 'SCEF', '5m', '5L', '5mv'},...
    {'Premotor Cortex','55b', '6d', '6a', 'FEF', '6v', '6r', 'PEF'},...
    {'Posterior Opercular Cortex','43', 'FOP1', 'OP4', 'OP1', 'OP2-3', 'PFcm'},...
    {'Early Auditory Cortex','A1', 'LBelt', 'MBelt', 'PBelt', 'RI'},...
    {'Auditory Association Cortex','A4', 'A5', 'STSdp', 'STSda', 'STSvp', 'STSva', 'STGa', 'TA2'},...
    {'Insular and Frontal Opercular Cortex','52', 'PI', 'Ig', 'PoI1', 'PoI2', 'FOP2', 'FOP3', ...
    'MI', 'AVI', 'AAIC', 'Pir', 'FOP4', 'FOP5'},...
    {'Medial Temporal Cortex','H', 'PreS', 'EC', 'PeEc', 'PHA1', 'PHA2', 'PHA3'},...
    {'Lateral Temporal Cortex','PHT', 'TE1p', 'TE1m', 'TE1a', 'TE2p', 'TE2a', ...
    'TGv', 'TGd', 'TF'},...
    {'Temporo-Parieto-Occipital Junction','TPOJ1', 'TPOJ2', 'TPOJ3', 'STV', 'PSL'},...
    {'Superior Parietal Cortex','LIPv', 'LIPd', 'VIP', 'AIP', 'MIP', ...
    '7PC', '7AL', '7Am', '7PL', '7Pm'},...
    {'Inferior Parietal Cortex','PGp', 'PGs', 'PGi', 'PFm', 'PF', 'PFt', 'PFop', ...
    'IP0', 'IP1', 'IP2'},...
    {'Posterior Cingulate Cortex','DVT', 'ProS', 'POS1', 'POS2', 'RSC', 'v23ab', 'd23ab', ...
    '31pv', '31pd', '31a', '23d', '23c', 'PCV', '7m'},...
    {'Anterior Cingulate and Medial Prefrontal Cortex','33pr', 'p24pr', 'a24pr', 'p24', 'a24', 'p32pr', 'a32pr', 'd32', ...
    'p32', 's32', '8BM', '9m', '10v', '10r', '25',},...
    {'Orbital and Polar Frontal Cortex','47s', '47m', 'a47r', '11l', '13l',...
    'a10p', 'p10p', '10pp', '10d', 'OFC', 'pOFC',},...
    {'Inferior Frontal Cortex','44', '45', 'IFJp', 'IFJa', 'IFSp', 'IFSa', '47l', 'p47r',},...
    {'DorsoLateral Prefrontal Cortex','8C', '8Av', 'i6-8', 's6-8', 'SFL', '8BL', '9p', '9a', '8Ad',...
    'p9-46v', 'a9-46v', '46', '9-46d',}};


%%
groups_labels = {{'Prim Visual C. (V1)'}, ...
    {'Early Vis C.'}, ...
    {'Dors Stream Vis C.'}, ...
    {'Vent Stream Vis C.'}, ...
    {'MT+ Complex and Neighboring Vis Areas'},...
    {'Somatosensory and Motor C.'},...
    {'Paracentral Lobular and Mid Cin C.',},...
    {'Premotor C.'},...
    {'Post Opercular C.'},...
    {'Early Aud C.'},...
    {'Aud Association C.'},...
    {'Insular and Front Oper C.'},...
    {'Med Temp C.'},...
    {'Lateral Temp C.'},...
    {'Temporo-Parieto-Occip Junction'},...
    {'Sup Pari C.'},...
    {'Inf Pari C.'},...
    {'Post Cin C.'},...
    {'Ant Cin and Med PreFront C.'},...
    {'Orbital and Polar Front C.'},...
    {'Inf Front C.'},...
    {'DorsoLateral PreFront C.'}};


end
